/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '975115' at '1/23/17 4:22 PM' with Gradle 3.1
 *
 * @author 975115, @date 1/23/17 4:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
